### ISSUE TITLE
pipelining requests?

### ISSUE THREAD

**Issue by Dowwie** [benashford/redis-async-rs#19]
I thought that the explanation about implicit pipelining requires clarification.  Are you suggesting that explicit pipelining redis requests, within a single batch, is no longer needed, due to the nature of how requests are sent (in order, ...) to redis?

**Comment by benashford** [comment]
Yes, that part could do with some clarification as it doesn't really go into detail.  The implicit pipelining comes from a combination of how Tokio works, and the specific implementation of this library.

The basic connection is just that, a `Sink` and `Stream` (as defined in Futures) of Redis messages back-and-forth to the Redis server.  But the `PairedConnection` is a higher-level interface where specific commands can be issued, and a specific `Future` for the result of that particular command returned, similar to synchronous Redis clients, this uses the basic connection underneath.

The goal was that a single `PairedConnection` could be shared by cloning wherever it needed to go, different structs can retain it, can be cloned across threads etc.  So that in many apps a single connection is all that is required (depending on intended use, of course).  As such the connection itself is not absorbed into the future when issuing a command, instead the command is added to a queue, the queue is worked by a future that is spawned on to the Tokio runtime at the time the connection is opened.  This allows many commands to be issued, and sent to Redis, and responses dealt with later.  The futures returned by the `send` function are just thin wrappers around `futures::mpsc::oneshot` channels fed by the same spawned future.

The implementation of the spawned future is simple: it takes as many queued commands as it can, and writes them to the socket until either: a) there are none left, or b) the underlying Tokio socket reports it is full, which ever happens first.  Then does the same in reverse, reading from Redis.  If there's no work to do, Tokio wakes up the task when the queue receives a message or the socket receives some data.

Commands can be sent to Redis ahead of the previous command being answered.  The result of this is that pipelining is implicit.  Rather than defining a batch of commands to send to Redis, and get a batch of responses back, if an app can issue commands faster than they can be sent to Redis, they'll be packed into batches (essentially the size of Tokio's buffer for TCP connections).

There are limits, of course.  If an app needs to wait for a response before issuing a follow-up command, then these will have to be sent individually.  The benchmark results show this happening: https://github.com/benashford/redis-async-rs#performance. The `simple_getsetdel` test was written in such a way that commands were dependent on previous commands, so the performance was closer to the non-pipelined equivalent test in another Redis client; but the `complex` test behaved like the pipelined equivalent; but in neither test was there any explicit pipelining: https://github.com/benashford/redis-async-rs/blob/master/benches/benchmarks.rs

I'm not sure this explains it fully, I'll try and refine it and update the README with something coherent.

**Comment by Dowwie** [comment]
@benashford this may be one of the best responses I could have ever asked for.  If I could give you a github gold star, I would *right now*. :)  Thank you for taking the time to explain this in more detail.  I have been trying to port synchronous redis-rs code I've written and extensively use PIPE to send calls over to redis in a single block.  Essentially, I want to send the calls all over at once and return control when all of the redis futures are finished.  Not sure whether I can sufficiently gather how to do this from the complex example, though.  For instance, suppose I am writing some cache invalidation logic.  In this example, suppose that entails deleting 5 keys from redis: key1, key2, key3, key4, and key5.  

```rust
pipe.del(&key1)
       .del(&key2)
       .del(&key3)
       .del(&key4)
       .del(&key5)
       .query(&conn)?;
```

**Comment by benashford** [comment]
One thing that this library doesn't support is transactions (e.g. the MULTI and EXEC commands), but assuming that those five deletes do not need to be atomic, as long as they're all deleted, then it can be done by sending five commands:

```rust
let result1 = connection.send(resp_array!["DEL", &key1]);
let result2 = connection.send(resp_array!["DEL", &key2]);
// and so on...
```

And then joining the futures using `join` or `join_all` from the futures library.

Or easier in a loop possibly if you had a vector of keys.

```rust
let results: Vec<_> = keys.iter().map(|key| con.send(resp_array!["DEL", key])).collect();
future::join_all(results)
```

This would return a future which returns the item of `Vec<i64>` where each element corresponds to each original `DEL` command in turn.

(Also, of course, the `DEL` command can take multiple arguments, so you could delete five keys with just one command, but the above is the general principal.)
