### ISSUE TITLE
EXPIRE not working?

### ISSUE THREAD

**Issue by Dowwie** [benashford/redis-async-rs#21]
Hey Ben

Is something wrong with the EXPIRE command using the resp_array macro?  I get a run-time exception but am unsure whether the issue lies with my syntax, redis-async, or actix-redis (which uses redis-async).
    resp_array!["EXPIRE", my_key, 90]

Error:
    Error("ERR Protocol error: expected \'$\', got \':\'")

UPDATE:  the seconds must be expressed as a String or &str.  :-1:

**Comment by benashford** [comment]
At present redis-async doesn't enforce the structure of Redis commands.  I have considered doing that, but at the moment it doesn't because otherwise every new Redis release would be incompatible until redis-async catches up and adds new commands/options/etc.  This is why `resp_array!` exists as a macro, to make it easy to construct a Redis command, but it does mean it's up to the calling application to ensure the command is formatted correctly for the version of Redis used.

In this specific case of EXPIRE, I think it's because Redis is expecting the timeout option to be presented as a String.  So `resp_array!["EXPIRE", my_key, "90"]` ought to do the job.

I should add this as documentation on `PairedConnect::send` (and similar functions elsewhere).
