### ISSUE TITLE
PSUBSCRIBE support

### ISSUE THREAD

**Issue by GopherJ** [benashford/redis-async-rs#33]
Hello, do you have a plan for supporting `PSUBSCRIBE` command? Thanks in  advance for your reply.

**Comment by benashford** [comment]
Hello,

I haven't ruled-out supporting `PSUBSCRIBE`, but I haven't yet had the need to include it.

In theory it could be added to the current Pub/Sub implementation without significant changes. We should definitely consider it as an option for future versions.

**Comment by GopherJ** [comment]
hello @benashford , our use case for `PSUBSCRIBE` is in our real time positions engine, we need to seperate for example region/zone/map.

we have keys like `positions.application_namespace.level.zone`, in this situation if we would like to subscribe all the incoming positions, we need to use psubscribe on `positions.*

**Comment by GopherJ** [comment]
Hi @benashford, could you review this PR: #57

**Comment by benashford** [comment]
This is now published in:

* `0.6.4` - which is Tokio 0.2 compatible.
* `0.7.1` - which is Tokio 0.3 compatible.

(I'm keeping both branches maintained for a while because I think most users - myself included in a private repo I maintain - have Tokio 0.2 dependencies for a while yet, but hopefully not for too long.)
