### ISSUE TITLE
how to connect redis with password

### ISSUE THREAD

**Issue by panicfrog** [benashford/redis-async-rs#49]
i don't konw how to connect redis with password

**Comment by benashford** [comment]
Hello,

There's no specific support for Redis authentication in this library yet. There's no "connect with password" function, largely because in the use-cases to which it has currently been applied, there's been no need.

But it can still be used to connect to Redis servers that need a password by sending the AUTH command yourself. So something like:

```rust
    let connection = client::paired_connect(&addr).await?;
    match connection.send(resp_array!["AUTH", password]).await {
        Ok(()) => println!("Authenticated"),
        Err(e) => eprintln!("Error authenticating {}", e)
    }
```

**Comment by panicfrog** [comment]
think you
