### ISSUE TITLE
EXPIRE not working?

### ISSUE THREAD

**Issue by zuiyu1998** [benashford/redis-async-rs#79]
resp_array!["EXPIRE", my_key, "90"] is failing.
Error:
Error("Unexpected  value, should be encoded as a SimpleString: Some(Integer(1))")
#21

**Comment by benashford** [comment]
The issue with #21 was the wrong parameters in `resp_array!` but the issue here isn't that, they're correct. The error message in this case is an error processing the response from Redis itself.

The EXPIRE command returns an integer response (https://redis.io/commands/expire/), but the error message indicates that it was trying to read a string response instead.

This could happen with code like:

```rust
    connection.send(resp_array!["EXPIRE", my_key, "90"]).await?;
```

(i.e. where the response type isn't specified so a `()` is assumed by the compiler).

But on the other hand the library maps integer `0` and `1` response (as Redis provides for the EXPIRE command) to `bool` so this will work:

```rust
    let successful: bool = connection.send(resp_array!["EXPIRE", my_key, "90"]).await?;
```
